name: Build & Publish

on: 
  - push

jobs:
  xenial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2
      with:
        name: endless-sky-docker-images/xenial
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: xenial.Dockerfile